### ISSUE TITLE
cannot set comment status

### ISSUE THREAD

**Issue by Blatant** [hissy/rs-csv-importer#39]
Hi,

THanks for a great plugin, I added a column to my CSV for the comment_status column of the wp_posts table, but this value is imported as a custom field instead of setting the base column value. 

I wish to import a large number of Posts (1000+) but editing each one to disable comments... Might be best to manually import them....

If you can help at all I'd appriciate it!

**Comment by hissy** [comment]
I've added the feature to my plugin. Please check out the latest master branch.
I'll include this new feature in the next release.

Thanks!

**Comment by Blatant** [comment]
Hi hissy,

Thanks so much, thats awesome! Great support! 

Kind Regards.

Blatant

**Comment by hissy** [comment]
:+1:
