### ISSUE TITLE
Taxonomy terms should be automatically populated if they don't exist

### ISSUE THREAD

**Issue by abrahamvelazquez** [hissy/rs-csv-importer#45]
`post_category` and `post_tags` are automatically added if they don't exists, but this is not the case for custom taxonomies. This would be a very handy feature.

> `post_category`: (string, comma separated) slug of post categories
> `post_tags`: (string, comma separated) name of post tags
> `tax_{taxonomy}`: (string, comma separated) Any field prefixed with `tax_` will be used as a custom taxonomy. Taxonomy must already exist. Entries are names or slugs of terms.

**Comment by abrahamvelazquez** [comment]
Actually... I tested on a fresh install and it looks like the import did automatically add taxonomies that didn't exist. Can anyone confirm? The docs can be updated.

**Comment by hissy** [comment]
What is the problem?

**Comment by abrahamvelazquez** [comment]
No problem. I just looks like my original request already works. Can you confirm?
