### ISSUE TITLE
Endlessly Increasing Memory Usage while Importing Huge CSV

### ISSUE THREAD

**Issue by gitusp** [hissy/rs-csv-importer#49]
Hello, @hissy.

I tried to import a huge CSV which contains over 50,000 lines and got a fatal error, memory exhausted.
I figured out that when `wp_insert_post` method is called, WP creates cache and the cache causes memory shortage.

So can I just add `wp_cache_flush();` below this line?:
https://github.com/hissy/rs-csv-importer/blob/master/rs-csv-importer.php#L421
(I've confirmed that `wp_cache_flush();` eases memory usage and imported the huge CSV successfully.)

I'll open a pull-request if you'd think it's ok.
Thanks.

**Comment by hissy** [comment]
Hi @gitusp , thank you for your suggestion. Please open a new request, then I'll be able to review it.

**Comment by gitusp** [comment]
Thanks @hissy. I've opened #50.
