### ISSUE TITLE
How To Replace Field Value With Null?

### ISSUE THREAD

**Issue by stripitdown** [hissy/rs-csv-importer#65]
Not so much an issue, but a question.

If I have Post Object fields with values in, is it possible to replace these with NULL values? I can't leave cells in the CSV file empty as this means 'keep it' – and filling these cells with \N or NULL is unsuccessful.

**Comment by hissy** [comment]
It isn't possible to delete post meta value. You can replace the function with really_simple_csv_importer_class filter.
